# Macro file for the initialisation
# in interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 1

# Initialize kernel
/run/initialize

/beam/specDir /data/McDCIR_PDC_chk/spectra
/beam/kVp 80
/beam/angle 60
/beam/radius 40
/beam/lower 0
/beam/upper 40
# Source setting
#/control/execute source.mac

# Visualization setting
/control/execute vis.mac
