# Macro file for the initialisation
# in interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 1

# Initialize kernel
/run/initialize

# Source setting
/internal/surface "9500 9700"
/gun/particle gamma
/gun/energy 0.1 MeV

# Visualization setting
/control/execute vis.mac
