# Lightweight visualization for the large tetrahedral phantom.
/vis/open OGL 800x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/viewer/set/specialMeshRendering
/vis/viewer/set/specialMeshRenderingOption surfaces
/vis/drawVolume
/vis/geometry/set/visibility worldLogical 0 false
/vis/geometry/set/visibility phantomLogical 0 false
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge false
/vis/viewer/set/background 1 1 1 1
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/zoomTo 5
/vis/viewer/set/viewpointVector 0 -1 0
/vis/viewer/set/targetPoint 0 0 0 mm
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
